/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Story = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Principal,
  'authorName' : IDL.Text,
  'authorPhoto' : IDL.Opt(IDL.Text),
  'imageUrl' : IDL.Text,
  'timestamp' : IDL.Int,
  'caption' : IDL.Text,
  'likesCount' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CallType = IDL.Variant({ 'video' : IDL.Null, 'voice' : IDL.Null });
export const CallSignalType = IDL.Variant({
  'iceCandidate' : IDL.Null,
  'offer' : IDL.Null,
  'callEnd' : IDL.Null,
  'answer' : IDL.Null,
  'callDecline' : IDL.Null,
});
export const CallSignal = IDL.Record({
  'id' : IDL.Nat,
  'data' : IDL.Text,
  'toUserId' : IDL.Principal,
  'callType' : CallType,
  'fromUserId' : IDL.Principal,
  'timestamp' : IDL.Int,
  'signalType' : CallSignalType,
});
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const Profile = IDL.Record({
  'age' : IDL.Nat,
  'bio' : IDL.Text,
  'occupation' : IDL.Text,
  'height' : IDL.Text,
  'aboutMe' : IDL.Text,
  'favoriteSongs' : IDL.Vec(IDL.Text),
  'interests' : IDL.Vec(IDL.Text),
  'userId' : IDL.Principal,
  'mood' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'education' : IDL.Text,
  'photoUrl' : IDL.Opt(IDL.Text),
  'motherTongue' : IDL.Text,
  'gender' : Gender,
  'favoriteMovies' : IDL.Vec(IDL.Text),
  'mediaUrls' : IDL.Vec(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
  'religion' : IDL.Text,
  'thoughts' : IDL.Text,
  'maritalStatus' : IDL.Text,
  'location' : IDL.Text,
  'hobbies' : IDL.Vec(IDL.Text),
});
export const CallStatus = IDL.Variant({
  'completed' : IDL.Null,
  'missed' : IDL.Null,
  'declined' : IDL.Null,
});
export const CallHistory = IDL.Record({
  'status' : CallStatus,
  'withUserId' : IDL.Principal,
  'callType' : CallType,
  'durationSeconds' : IDL.Nat,
  'timestamp' : IDL.Int,
});
export const MessageWithMeta = IDL.Record({
  'id' : IDL.Nat,
  'isDeleted' : IDL.Bool,
  'read' : IDL.Bool,
  'text' : IDL.Text,
  'toUserId' : IDL.Principal,
  'fromUserId' : IDL.Principal,
  'timestamp' : IDL.Int,
  'reaction' : IDL.Opt(IDL.Text),
});
export const StoryNotifType = IDL.Variant({
  'like' : IDL.Null,
  'comment' : IDL.Null,
  'reply' : IDL.Null,
});
export const StoryNotification = IDL.Record({
  'id' : IDL.Nat,
  'actorName' : IDL.Text,
  'notifType' : StoryNotifType,
  'storyId' : IDL.Nat,
  'storyOwnerId' : IDL.Principal,
  'actorPhoto' : IDL.Opt(IDL.Text),
  'text' : IDL.Text,
  'actorUserId' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const PrivacyVisibility = IDL.Variant({
  'everyone' : IDL.Null,
  'matchesOnly' : IDL.Null,
  'hidden' : IDL.Null,
});
export const StoryComment = IDL.Record({
  'id' : IDL.Nat,
  'parentCommentId' : IDL.Opt(IDL.Nat),
  'userId' : IDL.Principal,
  'storyId' : IDL.Nat,
  'text' : IDL.Text,
  'authorName' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptMatchRequest' : IDL.Func([IDL.Principal], [], []),
  'addStory' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addStoryComment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'addStoryReaction' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'adminDeleteProfile' : IDL.Func([IDL.Principal], [], []),
  'adminDeleteStory' : IDL.Func([IDL.Nat], [], []),
  'adminGetAllStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'consumeCallSignals' : IDL.Func([IDL.Principal], [IDL.Vec(CallSignal)], []),
  'createOrUpdateProfile' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        Gender,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'declineMatchRequest' : IDL.Func([IDL.Principal], [], []),
  'deleteMessage' : IDL.Func([IDL.Nat], [], []),
  'deleteStory' : IDL.Func([IDL.Nat], [], []),
  'editMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'getAllProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'getAllWithRequestedCount' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Profile, IDL.Nat))],
      ['query'],
    ),
  'getCallHistory' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(CallHistory, Profile))],
      ['query'],
    ),
  'getCallerStoryReaction' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMatchRequests' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Tuple(
            Profile,
            IDL.Variant({
              'pending' : IDL.Null,
              'accepted' : IDL.Null,
              'declined' : IDL.Null,
            }),
          )
        ),
      ],
      ['query'],
    ),
  'getMessages' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(MessageWithMeta)],
      ['query'],
    ),
  'getMutualMatches' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'getMyStoryNotifications' : IDL.Func(
      [],
      [IDL.Vec(StoryNotification)],
      ['query'],
    ),
  'getPremiumStatus' : IDL.Func([], [IDL.Bool], ['query']),
  'getPrivacyVisibility' : IDL.Func([], [PrivacyVisibility], ['query']),
  'getShowLastActive' : IDL.Func([], [IDL.Bool], ['query']),
  'getStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
  'getStoryComments' : IDL.Func([IDL.Nat], [IDL.Vec(StoryComment)], ['query']),
  'getStoryReactions' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getStoryViewCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getStoryViewers' : IDL.Func([IDL.Nat], [IDL.Vec(Profile)], ['query']),
  'getTypingStatus' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'hasLikedStory' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeStory' : IDL.Func([IDL.Nat], [], []),
  'logCall' : IDL.Func([IDL.Principal, CallType, IDL.Nat, CallStatus], [], []),
  'markMessageRead' : IDL.Func([IDL.Nat], [], []),
  'reactToMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'recordStoryView' : IDL.Func([IDL.Nat], [], []),
  'replyToStoryComment' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'searchProfiles' : IDL.Func([IDL.Text], [IDL.Vec(Profile)], ['query']),
  'sendMatchRequest' : IDL.Func([IDL.Principal], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'setPremiumStatus' : IDL.Func([IDL.Bool], [], []),
  'setPrivacyVisibility' : IDL.Func([PrivacyVisibility], [], []),
  'setShowLastActive' : IDL.Func([IDL.Bool], [], []),
  'setTyping' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  'storeCallSignal' : IDL.Func(
      [IDL.Principal, CallSignalType, IDL.Text, CallType],
      [],
      [],
    ),
  'unlikeStory' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Story = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Principal,
    'authorName' : IDL.Text,
    'authorPhoto' : IDL.Opt(IDL.Text),
    'imageUrl' : IDL.Text,
    'timestamp' : IDL.Int,
    'caption' : IDL.Text,
    'likesCount' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CallType = IDL.Variant({ 'video' : IDL.Null, 'voice' : IDL.Null });
  const CallSignalType = IDL.Variant({
    'iceCandidate' : IDL.Null,
    'offer' : IDL.Null,
    'callEnd' : IDL.Null,
    'answer' : IDL.Null,
    'callDecline' : IDL.Null,
  });
  const CallSignal = IDL.Record({
    'id' : IDL.Nat,
    'data' : IDL.Text,
    'toUserId' : IDL.Principal,
    'callType' : CallType,
    'fromUserId' : IDL.Principal,
    'timestamp' : IDL.Int,
    'signalType' : CallSignalType,
  });
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const Profile = IDL.Record({
    'age' : IDL.Nat,
    'bio' : IDL.Text,
    'occupation' : IDL.Text,
    'height' : IDL.Text,
    'aboutMe' : IDL.Text,
    'favoriteSongs' : IDL.Vec(IDL.Text),
    'interests' : IDL.Vec(IDL.Text),
    'userId' : IDL.Principal,
    'mood' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'education' : IDL.Text,
    'photoUrl' : IDL.Opt(IDL.Text),
    'motherTongue' : IDL.Text,
    'gender' : Gender,
    'favoriteMovies' : IDL.Vec(IDL.Text),
    'mediaUrls' : IDL.Vec(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
    'religion' : IDL.Text,
    'thoughts' : IDL.Text,
    'maritalStatus' : IDL.Text,
    'location' : IDL.Text,
    'hobbies' : IDL.Vec(IDL.Text),
  });
  const CallStatus = IDL.Variant({
    'completed' : IDL.Null,
    'missed' : IDL.Null,
    'declined' : IDL.Null,
  });
  const CallHistory = IDL.Record({
    'status' : CallStatus,
    'withUserId' : IDL.Principal,
    'callType' : CallType,
    'durationSeconds' : IDL.Nat,
    'timestamp' : IDL.Int,
  });
  const MessageWithMeta = IDL.Record({
    'id' : IDL.Nat,
    'isDeleted' : IDL.Bool,
    'read' : IDL.Bool,
    'text' : IDL.Text,
    'toUserId' : IDL.Principal,
    'fromUserId' : IDL.Principal,
    'timestamp' : IDL.Int,
    'reaction' : IDL.Opt(IDL.Text),
  });
  const StoryNotifType = IDL.Variant({
    'like' : IDL.Null,
    'comment' : IDL.Null,
    'reply' : IDL.Null,
  });
  const StoryNotification = IDL.Record({
    'id' : IDL.Nat,
    'actorName' : IDL.Text,
    'notifType' : StoryNotifType,
    'storyId' : IDL.Nat,
    'storyOwnerId' : IDL.Principal,
    'actorPhoto' : IDL.Opt(IDL.Text),
    'text' : IDL.Text,
    'actorUserId' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const PrivacyVisibility = IDL.Variant({
    'everyone' : IDL.Null,
    'matchesOnly' : IDL.Null,
    'hidden' : IDL.Null,
  });
  const StoryComment = IDL.Record({
    'id' : IDL.Nat,
    'parentCommentId' : IDL.Opt(IDL.Nat),
    'userId' : IDL.Principal,
    'storyId' : IDL.Nat,
    'text' : IDL.Text,
    'authorName' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptMatchRequest' : IDL.Func([IDL.Principal], [], []),
    'addStory' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addStoryComment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'addStoryReaction' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'adminDeleteProfile' : IDL.Func([IDL.Principal], [], []),
    'adminDeleteStory' : IDL.Func([IDL.Nat], [], []),
    'adminGetAllStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'consumeCallSignals' : IDL.Func([IDL.Principal], [IDL.Vec(CallSignal)], []),
    'createOrUpdateProfile' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          Gender,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'declineMatchRequest' : IDL.Func([IDL.Principal], [], []),
    'deleteMessage' : IDL.Func([IDL.Nat], [], []),
    'deleteStory' : IDL.Func([IDL.Nat], [], []),
    'editMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'getAllProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'getAllWithRequestedCount' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Profile, IDL.Nat))],
        ['query'],
      ),
    'getCallHistory' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(CallHistory, Profile))],
        ['query'],
      ),
    'getCallerStoryReaction' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMatchRequests' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Tuple(
              Profile,
              IDL.Variant({
                'pending' : IDL.Null,
                'accepted' : IDL.Null,
                'declined' : IDL.Null,
              }),
            )
          ),
        ],
        ['query'],
      ),
    'getMessages' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(MessageWithMeta)],
        ['query'],
      ),
    'getMutualMatches' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'getMyStoryNotifications' : IDL.Func(
        [],
        [IDL.Vec(StoryNotification)],
        ['query'],
      ),
    'getPremiumStatus' : IDL.Func([], [IDL.Bool], ['query']),
    'getPrivacyVisibility' : IDL.Func([], [PrivacyVisibility], ['query']),
    'getShowLastActive' : IDL.Func([], [IDL.Bool], ['query']),
    'getStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
    'getStoryComments' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(StoryComment)],
        ['query'],
      ),
    'getStoryReactions' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getStoryViewCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getStoryViewers' : IDL.Func([IDL.Nat], [IDL.Vec(Profile)], ['query']),
    'getTypingStatus' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'hasLikedStory' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeStory' : IDL.Func([IDL.Nat], [], []),
    'logCall' : IDL.Func(
        [IDL.Principal, CallType, IDL.Nat, CallStatus],
        [],
        [],
      ),
    'markMessageRead' : IDL.Func([IDL.Nat], [], []),
    'reactToMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'recordStoryView' : IDL.Func([IDL.Nat], [], []),
    'replyToStoryComment' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'searchProfiles' : IDL.Func([IDL.Text], [IDL.Vec(Profile)], ['query']),
    'sendMatchRequest' : IDL.Func([IDL.Principal], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'setPremiumStatus' : IDL.Func([IDL.Bool], [], []),
    'setPrivacyVisibility' : IDL.Func([PrivacyVisibility], [], []),
    'setShowLastActive' : IDL.Func([IDL.Bool], [], []),
    'setTyping' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
    'storeCallSignal' : IDL.Func(
        [IDL.Principal, CallSignalType, IDL.Text, CallType],
        [],
        [],
      ),
    'unlikeStory' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };