/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CallHistory {
  'status' : CallStatus,
  'withUserId' : Principal,
  'callType' : CallType,
  'durationSeconds' : bigint,
  'timestamp' : bigint,
}
export interface CallSignal {
  'id' : bigint,
  'data' : string,
  'toUserId' : Principal,
  'callType' : CallType,
  'fromUserId' : Principal,
  'timestamp' : bigint,
  'signalType' : CallSignalType,
}
export type CallSignalType = { 'iceCandidate' : null } |
  { 'offer' : null } |
  { 'callEnd' : null } |
  { 'answer' : null } |
  { 'callDecline' : null };
export type CallStatus = { 'completed' : null } |
  { 'missed' : null } |
  { 'declined' : null };
export type CallType = { 'video' : null } |
  { 'voice' : null };
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export interface Message {
  'id' : bigint,
  'read' : boolean,
  'text' : string,
  'toUserId' : Principal,
  'fromUserId' : Principal,
  'timestamp' : bigint,
}
export interface Profile {
  'age' : bigint,
  'bio' : string,
  'occupation' : string,
  'height' : string,
  'aboutMe' : string,
  'favoriteSongs' : Array<string>,
  'interests' : Array<string>,
  'userId' : Principal,
  'mood' : string,
  'name' : string,
  'createdAt' : bigint,
  'education' : string,
  'photoUrl' : [] | [string],
  'motherTongue' : string,
  'gender' : Gender,
  'favoriteMovies' : Array<string>,
  'mediaUrls' : Array<string>,
  'phone' : [] | [string],
  'religion' : string,
  'thoughts' : string,
  'maritalStatus' : string,
  'location' : string,
  'hobbies' : Array<string>,
}
export interface Story {
  'id' : bigint,
  'userId' : Principal,
  'authorName' : string,
  'authorPhoto' : [] | [string],
  'imageUrl' : string,
  'timestamp' : bigint,
  'caption' : string,
  'likesCount' : bigint,
}
export interface StoryComment {
  'id' : bigint,
  'parentCommentId' : [] | [bigint],
  'userId' : Principal,
  'storyId' : bigint,
  'text' : string,
  'authorName' : string,
  'timestamp' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptMatchRequest' : ActorMethod<[Principal], undefined>,
  'addStory' : ActorMethod<[string, string], undefined>,
  'addStoryComment' : ActorMethod<[bigint, string], undefined>,
  'adminDeleteProfile' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'consumeCallSignals' : ActorMethod<[Principal], Array<CallSignal>>,
  'createOrUpdateProfile' : ActorMethod<
    [
      string,
      bigint,
      Gender,
      string,
      string,
      string,
      [] | [string],
      string,
      string,
      string,
      string,
      Array<string>,
      Array<string>,
      string,
      Array<string>,
      Array<string>,
      string,
      string,
      Array<string>,
      string,
      [] | [string],
    ],
    undefined
  >,
  'declineMatchRequest' : ActorMethod<[Principal], undefined>,
  'getAllProfiles' : ActorMethod<[], Array<Profile>>,
  'getAllWithRequestedCount' : ActorMethod<[], Array<[Profile, bigint]>>,
  'getCallHistory' : ActorMethod<[], Array<[CallHistory, Profile]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMatchRequests' : ActorMethod<
    [],
    Array<
      [
        Profile,
        { 'pending' : null } |
          { 'accepted' : null } |
          { 'declined' : null },
      ]
    >
  >,
  'getMessages' : ActorMethod<[Principal], Array<Message>>,
  'getMutualMatches' : ActorMethod<[], Array<Profile>>,
  'getStories' : ActorMethod<[], Array<Story>>,
  'getStoryComments' : ActorMethod<[bigint], Array<StoryComment>>,
  'getTypingStatus' : ActorMethod<[Principal], boolean>,
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'hasLikedStory' : ActorMethod<[bigint], boolean>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likeStory' : ActorMethod<[bigint], undefined>,
  'logCall' : ActorMethod<[Principal, CallType, bigint, CallStatus], undefined>,
  'markMessageRead' : ActorMethod<[bigint], undefined>,
  'replyToStoryComment' : ActorMethod<[bigint, bigint, string], undefined>,
  'searchProfiles' : ActorMethod<[string], Array<Profile>>,
  'sendMatchRequest' : ActorMethod<[Principal], undefined>,
  'sendMessage' : ActorMethod<[Principal, string], undefined>,
  'setTyping' : ActorMethod<[Principal, boolean], undefined>,
  'storeCallSignal' : ActorMethod<
    [Principal, CallSignalType, string, CallType],
    undefined
  >,
  'unlikeStory' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];