/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface GiftRecord {
    id: bigint;
    giftEmoji: string;
    toUserId: Principal;
    fromUserId: Principal;
    timestamp: bigint;
    giftName: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getCallerUserRole(): Promise<UserRole>;
    getGiftsReceived(): Promise<Array<GiftRecord>>;
    getGiftsSent(): Promise<Array<GiftRecord>>;
    isCallerAdmin(): Promise<boolean>;
    sendGift(toUserId: Principal, giftName: string, giftEmoji: string): Promise<GiftRecord>;
}
import type { UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGiftsReceived(): Promise<Array<GiftRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGiftsReceived();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGiftsReceived();
            return result;
        }
    }
    async getGiftsSent(): Promise<Array<GiftRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGiftsSent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGiftsSent();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async sendGift(arg0: Principal, arg1: string, arg2: string): Promise<GiftRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.sendGift(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendGift(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}


// ---- Additional type exports for Bandhan Matrimonial app ----

export enum Gender {
  male = "male",
  female = "female",
  other = "other",
}

export interface Profile {
  userId: Principal;
  name: string;
  age: bigint;
  gender: Gender;
  religion: string;
  location: string;
  bio: string;
  photoUrl: string | null;
  occupation: string;
  height: string;
  motherTongue: string;
  maritalStatus: string;
  interests: string[];
  hobbies: string[];
  education: string;
  favoriteMovies: string[];
  favoriteSongs: string[];
  thoughts: string;
  mood: string;
  mediaUrls: string[];
  aboutMe: string;
  phone: string | null;
  createdAt: bigint;
}

export interface MessageWithMeta {
  id: bigint;
  fromUserId: Principal;
  toUserId: Principal;
  text: string;
  timestamp: bigint;
  read: boolean;
  reaction: string | null;
  isDeleted: boolean;
}

export interface Story {
  id: bigint;
  userId: Principal;
  authorName: string;
  authorPhoto: string | null;
  imageUrl: string;
  caption: string;
  timestamp: bigint;
  likesCount: bigint;
}

export interface StoryComment {
  id: bigint;
  storyId: bigint;
  userId: Principal;
  authorName: string;
  text: string;
  timestamp: bigint;
  parentCommentId: bigint | null;
}

export type StoryNotifType = "like" | "comment" | "reply";

export interface StoryNotification {
  id: bigint;
  storyId: bigint;
  storyOwnerId: Principal;
  actorUserId: Principal;
  actorName: string;
  actorPhoto: string | null;
  notifType: StoryNotifType;
  text: string;
  timestamp: bigint;
}

export enum CallSignalType {
  offer = "offer",
  answer = "answer",
  iceCandidate = "iceCandidate",
  callEnd = "callEnd",
  callDecline = "callDecline",
}

export enum CallType {
  video = "video",
  voice = "voice",
}

export interface CallSignal {
  id: bigint;
  fromUserId: Principal;
  toUserId: Principal;
  signalType: CallSignalType;
  callType: CallType;
  data: string;
  timestamp: bigint;
}

export enum CallStatus {
  completed = "completed",
  missed = "missed",
  declined = "declined",
}

export interface CallHistory {
  withUserId: Principal;
  callType: CallType;
  durationSeconds: bigint;
  status: CallStatus;
  timestamp: bigint;
}

export interface SuperLikeNotification {
  fromProfile: Profile;
  timestamp: bigint;
}

// AppBackend extends the generated interface with all app-level methods
export type AppBackend = backendInterface & {
  createOrUpdateProfile(
    name: string, age: bigint, gender: Gender, religion: string, location: string,
    bio: string, photoUrl: string | null, occupation: string, height: string,
    motherTongue: string, maritalStatus: string, interests: string[], hobbies: string[],
    education: string, favoriteMovies: string[], favoriteSongs: string[],
    thoughts: string, mood: string, mediaUrls: string[], aboutMe: string, phone: string | null
  ): Promise<void>;
  getCallerUserProfile(): Promise<Profile | null>;
  getUserProfile(userId: Principal): Promise<Profile | null>;
  getAllProfiles(): Promise<Profile[]>;
  searchProfiles(query: string): Promise<Profile[]>;
  adminDeleteProfile(profileId: Principal): Promise<void>;
  getAllWithRequestedCount(): Promise<Array<[Profile, bigint]>>;
  sendMatchRequest(toUser: Principal): Promise<void>;
  acceptMatchRequest(fromUser: Principal): Promise<void>;
  declineMatchRequest(fromUser: Principal): Promise<void>;
  getMatchRequests(): Promise<Array<[Profile, string]>>;
  getMutualMatches(): Promise<Profile[]>;
  sendMessage(toUserId: Principal, text: string): Promise<void>;
  getMessages(withUserId: Principal): Promise<MessageWithMeta[]>;
  markMessageRead(messageId: bigint): Promise<void>;
  reactToMessage(messageId: bigint, emoji: string): Promise<void>;
  editMessage(messageId: bigint, newText: string): Promise<void>;
  deleteMessage(messageId: bigint): Promise<void>;
  setTyping(toUserId: Principal, isTyping: boolean): Promise<void>;
  getTypingStatus(fromUserId: Principal): Promise<boolean>;
  addStory(imageUrl: string, caption: string): Promise<void>;
  getStories(): Promise<Story[]>;
  getStoryComments(storyId: bigint): Promise<StoryComment[]>;
  addStoryComment(storyId: bigint, text: string): Promise<void>;
  replyToStoryComment(storyId: bigint, parentCommentId: bigint, text: string): Promise<void>;
  likeStory(storyId: bigint): Promise<void>;
  unlikeStory(storyId: bigint): Promise<void>;
  hasLikedStory(storyId: bigint): Promise<boolean>;
  deleteStory(storyId: bigint): Promise<void>;
  adminDeleteStory(storyId: bigint): Promise<void>;
  adminGetAllStories(): Promise<Story[]>;
  getStoryReactions(storyId: bigint): Promise<Array<[string, bigint]>>;
  getCallerStoryReaction(storyId: bigint): Promise<string | null>;
  addStoryReaction(storyId: bigint, emoji: string): Promise<void>;
  getStoryViewCount(storyId: bigint): Promise<bigint>;
  getStoryViewers(storyId: bigint): Promise<Profile[]>;
  recordStoryView(storyId: bigint): Promise<void>;
  getMyStoryNotifications(): Promise<StoryNotification[]>;
  getPrivacyVisibility(): Promise<string>;
  setPrivacyVisibility(visibility: string): Promise<void>;
  getPremiumStatus(): Promise<boolean>;
  setPremiumStatus(value: boolean): Promise<void>;
  getShowLastActive(): Promise<boolean>;
  setShowLastActive(value: boolean): Promise<void>;
  storeCallSignal(toUserId: Principal, signalType: CallSignalType, data: string, callType: CallType): Promise<void>;
  consumeCallSignals(fromUserId: Principal): Promise<CallSignal[]>;
  logCall(withUserId: Principal, callType: CallType, durationSeconds: bigint, status: CallStatus): Promise<void>;
  getCallHistory(): Promise<Array<[CallHistory, Profile]>>;
  recordProfileView(userId: Principal): Promise<void>;
  getProfileViewCount(): Promise<bigint>;
  getProfileViewers(): Promise<Array<[Profile, bigint]>>;
  superLikeUser(userId: Principal): Promise<void>;
  unsuperLikeUser(userId: Principal): Promise<void>;
  hasSuperLiked(userId: Principal): Promise<boolean>;
  getSuperLikedBy(): Promise<Profile[]>;
  getSuperLikeNotifications(): Promise<SuperLikeNotification[]>;
  getDailySuggestions(): Promise<Profile[]>;
  startLive(title: string, matchesOnly: boolean): Promise<bigint>;
  getActiveLives(): Promise<LiveStream[]>;
  endLive(liveId: bigint): Promise<void>;
  getLiveMessages(liveId: bigint): Promise<LiveMessage[]>;
  sendLiveMessage(liveId: bigint, text: string): Promise<void>;
  getLiveViewers(liveId: bigint): Promise<Profile[]>;
  blockLiveUser(liveId: bigint, userId: Principal): Promise<void>;
  removeLiveUser(liveId: bigint, userId: Principal): Promise<void>;
  sendLiveReaction(liveId: bigint, emoji: string): Promise<void>;
  getLiveReactions(liveId: bigint): Promise<LiveReaction[]>;
  requestJoinLive(liveId: bigint, mode: string): Promise<void>;
  getLiveJoinRequests(liveId: bigint): Promise<Profile[]>;
  acceptLiveJoinRequest(liveId: bigint, userId: Principal): Promise<void>;
  joinLive(liveId: bigint): Promise<void>;
  leaveLive(liveId: bigint): Promise<void>;
  addLiveReaction(liveId: bigint, emoji: string): Promise<void>;
  blockFromLive(liveId: bigint, userId: Principal): Promise<void>;
  setLiveFilter(liveId: bigint, filter: unknown): Promise<void>;
}

export interface LiveStream {
  id: bigint;
  hostId: Principal;
  hostName: string;
  hostPhoto: string | null;
  title: string;
  startedAt: bigint;
  isActive: boolean;
  matchesOnly: boolean;
}

export interface LiveMessage {
  id: bigint;
  liveId: bigint;
  userId: Principal;
  userName: string;
  text: string;
  timestamp: bigint;
}

export interface LiveReaction {
  liveId: bigint;
  userId: Principal;
  emoji: string;
  timestamp: bigint;
}
